version: "{build}"

environment:
    global:
        HAXELIB_ROOT: C:\projects\haxelib

install:
    - cinst haxe -y
    - RefreshEnv
    - mkdir "%HAXELIB_ROOT%"
    - haxelib setup "%HAXELIB_ROOT%"
    - haxelib install hxcpp 3.1.39 > log.txt || type log.txt
    - haxelib list

build_script:
    - cd project
    - haxelib run hxcpp build.xml
    - haxelib run hxcpp build.xml -DHXCPP_M64
    - cd ..
    - haxelib dev hxudp .
    - haxe compile-cpp.hxml

test_script:
    - bin\UdpTest.exe